#!/bin/bash -l
#SBATCH -A uppmax2023-2-8 -M snowy
#SBATCH -p core
#SBATCH -n 16
#SBATCH -J BRAKER/Augustus-job
#SBATCH -t 3:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user andreas.bergfeldt.0189@student.uu.se

module load bioinfo-tools
module load braker/2.1.1_Perl5.24.1
module load augustus/3.2.3_Perl5.24.1
module load bamtools/2.5.1
module load blast/2.9.0+
module load GenomeThreader/1.7.0
module load samtools/1.8
module load GeneMark/4.33-es_Perl5.24.1

source $AUGUSTUS_CONFIG_COPY
cp -vf /sw/bioinfo/GeneMark/4.33-es/snowy/gm_key $HOME/.gm_key
chmod a+w -R /home/andreber/GenAn_proj_durian/code/augustus_config/

export SRCDR=$HOME/GenAn_proj_durian/results/BRAKER


samtools view -bS $HOME/GenAn_proj_durian/results/STAR/map/Aligned.out.sam > $HOME/GenAn_proj_durian/results/STAR/map/Aligned.out.bam

/sw/bioinfo/braker/2.1.1/snowy/braker.pl \
--AUGUSTUS_CONFIG_PATH=$HOME/GenAn_proj_durian/code/augustus_config/ \
--AUGUSTUS_BIN_PATH=/sw/bioinfo/augustus/3.4.0/snowy/bin/ \
--AUGUSTUS_SCRIPTS_PATH=/sw/bioinfo/augustus/3.4.0/snowy/scripts/ \
--GENEMARK_PATH=sw/bioinfo/GeneMark/4.33-es/snowy/ \
--species=durioZibethinus \
--genome=$HOME/GenAn_proj_durian/results/RepeatMasker/durian_pilon.fasta.masked \
--softmasking \
--bam=$HOME/GenAn_proj_durian/results/STAR/map/Aligned.out.bam \
--cores=16 \
--useexisting
