#!/bin/bash -l
#SBATCH -A uppmax2023-2-8 -M snowy
#SBATCH -p core
#SBATCH -n 4
#SBATCH -J BWA-job
#SBATCH -t 3:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user andreas.bergfeldt.0189@student.uu.se

module load bioinfo-tools bwa/0.7.17 samtools/1.17 

RESDIR=$HOME/GenAn_proj_durian/results

#bwa index $RESDIR/canu/canu_assmbly_durian.contigs.fasta

#bwa aln $RESDIR/canu/canu_assmbly_durian.contigs.fasta $RESDIR/trimmomatic/*P.fastq.gz > $RESDIR/BWA/durian_bwa_aligned.sai

bwa samse $RESDIR/canu/canu_assmbly_durian.contigs.fasta $RESDIR/BWA/durian_bwa_aligned.sai $RESDIR/trimmomatic/*P.fastq.gz > $RESDIR/BWA/durian_bwa_aligned.sam

samtools view -S -b $RESDIR/BWA/durian_bwa_aligned.sam > $RESDIR/BWA/durian_bwa_aligned.bam

export SRCDIR=$HOME/GenAn_proj_durian/results/BWA/


