#!/bin/bash -l
#SBATCH -A uppmax2023-2-8 -M snowy
#SBATCH -p core
#SBATCH -n 8
#SBATCH -J STAR-job
#SBATCH -t 15:00 --qos=short


module load bioinfo-tools star/2.7.9a 

export SRCDIR=$HOME/GenAn_proj_durian/results/STAR/map

cp $HOME/GenAn_proj_durian/results/trimmomatic/trimmomatic_transcriptome*P.fastq.gz $SNIC_TMP
cd $SNIC_TMP

STAR \
--runThreadN 8 \
--genomeDir $HOME/GenAn_proj_durian/results/STAR/index \
--readFilesIn $SNIC_TMP/*.gz \
--readFilesCommand zcat

cp *Log.out $SRCDIR
cp  *.sam $SRCDIR
