#!/bin/bash -l
#SBATCH -A uppmax2023-2-8 -M snowy
#SBATCH -p core
#SBATCH -n 8
#SBATCH -J STAR-job
#SBATCH -t 15:00 --qos=short


module load bioinfo-tools star/2.7.9a 

export SRCDIR=/crex/proj/genomeanalysis2023/nobackup/work/andreasb/results/STAR/diffexp/index/

cp $HOME/GenAn_proj_durian/results/RepeatMasker/** $SNIC_TMP
cd $SNIC_TMP

STAR \
--runThreadN 8 \
--runMode genomeGenerate \
--genomeDir $SRCDIR \
--genomeFastaFiles $SNIC_TMP/*.masked \
--genomeSAindexNbases 11 \
--sjdbGTFfile $HOME/GenAn_proj_durian/code/braker/durioZibethinus/augustus.hints.gtf



cp ** $SRCDIR
