#!/bin/bash -l
#SBATCH -A uppmax2023-2-8 -M snowy
#SBATCH -p core
#SBATCH -n 8
#SBATCH -J STAR-job
#SBATCH -t 15:00 --qos=short


module load bioinfo-tools star/2.7.9a 

export SRCDIR=$HOME/GenAn_proj_durian/results/STAR/index

cp $HOME/GenAN_proj_durian/results/RepeatMasker/** $SNIC_TMP
cd $SNIC_TMP

STAR \
--runThreadN 8 \
--runMode genomeGenerate \
--genomeDir $HOME/GenAN_proj_durian/results/STAR/index \
--genomeFastaFiles $SNIC_TMP/*.masked

cp ** $SRCDIR
