#!/bin/bash -l
#SBATCH -A uppmax2023-2-8 -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J trinity-run
#SBATCH -t 24:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user andreas.bergfeldt.0189@student.uu.se

module load bioinfo-tools trinity/2.4.0

export SRCDIR=$HOME/GenAn_proj_durian/results/trinity

trin_data=$HOME/GenAn_proj_durian/raw_data/4_Tean_Teh_2017/transcriptome

Trinity --seqType fastq.gz \        
--single trin_data/trimmed/*.gz \      
--output trinity_output_dir \
1>trinity.log 2>trinity.err
